# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1so19hmzoib5ipUb1gOVNze0EdTON8NGB
"""

# Import libraries
import cv2 # OpenCV: image reading/transformation, contours, etc.
import random # helps generate random numbers to select random images
import numpy as np # NumPy: arrays and data types (uint8) for masks/thresholds
import matplotlib.pyplot as plt # Used to display images and titles

imagenes = ['p1.jpg','p2.jpg','p3.jpg','p4.jpg','p5.jpg','p6.jpg']
nombre = ["Carlos","Rodrigo"]
contador = 0
puntaje_chuza = 0
# Scoreboard per player
puntajes = [0, 0]
puntajes_finales = [0, 0]
calculo1 = [0,0,0,0,0]
calculo2 = [0,0,0,0,0]

# For loop for the 3 rounds
for nom in range(2):
  for i in range(3):
    # Load image
    num = random.randint(0,5)
    img = cv2.imread(imagenes[num])

    # Convert to RGB
    img_RGB = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    img_gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    img_gausian = cv2.GaussianBlur(img_gray, (15,15),0)

    # White parameters
    lower_blanco = np.array([250, 250, 250], dtype = np.uint8)
    upper_blanco = np.array([255, 255, 255], dtype = np.uint8)

    # Mask and its application
    img_b = cv2.cvtColor(img_gausian,cv2.COLOR_GRAY2RGB)
    mask = cv2.inRange(img_b, lower_blanco, upper_blanco)
    result = cv2.bitwise_and(img_b,img_b, mask = mask)

    # Search for contours to count them
    canny = cv2.Canny(img_b,100,200)
    (contornos,_) = cv2.findContours(canny.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    # Display counted objects
    objetos = len(contornos)
    puntaje = abs(objetos - 10)

    if (nom == 0):
      calculo1[i] = puntaje
    if (nom == 1):
      calculo2[i] = puntaje

    puntajes[nom] = puntaje + puntajes[nom]
    contador = contador + 1

    # Plot
    plt.figure(figsize = (15,5))
    plt.title(f"Round {contador} - {nombre[nom]} | Pins: {objetos} | Round score: {puntaje}")
    plt.imshow(img_RGB, cmap = "gray")
    plt.axis("off")

# Calculate final score for player 1
for j in range(3):
  if (calculo1[j] == 10):
    puntaje_chuza = calculo1[j+1] + calculo1[j+2]
  puntajes_finales[0] += calculo1[j] + puntaje_chuza
  puntaje_chuza = 0

print(f"Total score Carlos:  {puntajes_finales[0]}")

# Calculate final score for player 2
for j in range(3):
  if (calculo2[j] == 10):
    puntaje_chuza = calculo2[j+1] + calculo2[j+2]
  puntajes_finales[1] += calculo2[j] + puntaje_chuza
  puntaje_chuza = 0

print(f"Total score Rodrigo: {puntajes_finales[1]}")

!sudo apt install tesseract-ocr
!pip install pytesseract
